-- vim.g.livepreview_previewer = 'zathura'
-- vim.g.livepreview_engine = 'xelatex'
vim.g.tex_flavor='latex'
vim.g.vimtex_view_method='zathura'
vim.g.vimtex_quickfix_mode=0
vim.g.tex_conceal='abdmg'
vim.g.vimtex_compliler_progname='nvr'
vim.g.vimtex_mappings_enabled = 0
vim.g.vimtex_text_obj_enabled = 0
vim.g.vimtex_motion_enabled = 0
