-- General
require('plugins')
require('keymappings')
require('settings')
require('colorscheme')
require('function')

-- Lsp
require('lsp.lua-ls')
require('lsp.md-ls')
require('lsp.py-ls')
require('lsp.ccls-ls')

-- Plugins
require('nv-autopair')
require('nv-bufferline')
require('nv-coderun')
require('nv-colorizer')
require('nv-commenter')
require('nv-compe')
require('nv-dashboard')
-- require('nv-debugger')
require('nv-diffview')
require('nv-easymotion')
require('nv-floaterm')
require('nv-focus')
require('nv-folder')
require('nv-galaxyline')
require('nv-git')
require('nv-header')
require('nv-indent-blankline')
require('nv-iswap')
require('nv-lsp-conf')
require('nv-markdown')
require('nv-nvim-tree')
require('nv-specs')
require('nv-telescope')
require('nv-treesitter')
require('nv-undotree')
